# Static (juliac/trim) path for parsing entrypoints.
# Keeps full type parameters for type-stable compiled code.

"""
    tryoptparse(parser, argv)
    tryoptparse(::Type{T}, argv) where {T<:AbstractLiftedParser}

Lower-level parsing entrypoint.

Returns a result container containing either the parsed value or a structured parse failure.
Unlike [`optparse`](@ref), this function does not throw on parse failures.

When called with a type generated by [`@parser`](@ref), delegates to
[`lift`](@ref) to retrieve the parser.
"""
@autospecialize pp function tryoptparse(
        pp::AbstractParser{T, E, S},
        args::Vector{String}
    )::ParseResult{T, Union{E, MainError}} where {T, E, S}

    UE = Union{E, MainError}
    canonical_argv, _ = normalize_argv(args)
    ctx = Context{S}(buffer = canonical_argv, state = pp.initialState, usage = usage(pp))

    while true
        mayberesult = parse(pp, ctx)::InnerParseResult{S, E}

        if is_error(mayberesult)
            err = unwrap_error(mayberesult)::InnerParseFailure{E}
            return Result{T, UE}(typedErr(UE, ℒ_error(err)))
        end
        result = unwrap(mayberesult)

        previous_buffer = ctx_remaining(ctx)
        ctx = res_nextctx(result)

        if no_progress(previous_buffer, ctx)
            return Result{T, UE}(typedErr(UE, MainError(MAIN_UnexpectedToken, ctx_peek(ctx))))
        end

        ctx_length(ctx) > 0 || break
    end

    state = ctx_state(ctx)
    res = complete(pp, state)::ParseResult{T, E}

    if is_error(res)
        return Result{T, UE}(typedErr(UE, unwrap_error(res)))
    else
        return Result{T, UE}(typedOk(T, unwrap(res)))
    end
end

"""
    optparse(parser, argv)
    optparse(::Type{T}, argv) where {T<:AbstractLiftedParser}

High-level parsing entrypoint.

When `juliac` mode is enabled, renders the error to `stderr` and returns
`nothing` on failure instead of throwing.

When called with a type generated by [`@parser`](@ref), delegates to
[`lift`](@ref) to retrieve the parser.

If you need stable non-throwing behavior across environments, use
[`tryoptparse`](@ref) instead.
"""
@autospecialize pp function optparse(pp::AbstractParser{T, E}, args::Vector{String}) where {T, E}
    mayberes = tryoptparse(pp, args)::ParseResult{T, Union{E, MainError}}

    if is_error(mayberes)
        errmsg = sprint(
            showerror, ParseException(
                pp, args, ParseError{E}(unwrap_error(mayberes))
            )
        )
        print(Core.stderr, "Error: ")
        println(Core.stderr, errmsg)
        return nothing
    end

    return unwrap(mayberes)
end

"""
    runparse(parser, argv; progname, help_command, help_flags, on_empty)
    runparse(::Type{T}, argv; ...) where {T<:AbstractLiftedParser}

Application-facing parsing entrypoint with built-in help handling.

See the main documentation for full keyword argument descriptions.

When called with a type generated by [`@parser`](@ref), delegates to
[`lift`](@ref) to retrieve the parser.
"""
@autospecialize parser function runparse(
        parser::AbstractParser, argv::Vector{String};
        progname = "",
        help_command = "help",
        help_flags = ["--help"],
        on_empty = isempty(help_command) ? [] : [help_command]
    )

    if isempty(argv)
        argv = on_empty
    end

    nargv, _ = normalize_argv(argv)
    newargv = String[]
    help_request = false
    for (i, token) in enumerate(nargv)
        if token == "--"
            append!(newargv, nargv[i:end])
            break
        end
        if token in help_flags
            help_request = true
            continue
        end
        push!(newargv, token)
    end

    if help_request
        print_help(Core.stderr, parser, newargv; progname)
        return nothing
    end

    if !isempty(help_command)
        _parser = or(hidden(helpcommand(help_command)), parser)
        res = optparse(_parser, newargv)
        if res isa HelpRequest
            print_help(Core.stderr, parser, res.argv; progname)
            return nothing
        end
        return res
    else
        return optparse(parser, newargv)
    end
end

# ─── Partial (passthrough) parser ─────────────────────────────────────────────

"""
    partial(parser)

Wrap a parser for partial argument consumption.

The resulting wrapper can be used with [`tryoptparse`](@ref) to parse only the
arguments that match, returning both the parsed value and any remaining
unconsumed tokens. Useful for wrapper CLIs that pass unrecognized arguments
through to a child program.

# Examples
```julia
wrapper = partial(record((; verbose = default(flag("--verbose"), false))))
result = tryoptparse(wrapper, ["--verbose", "--child-flag", "arg"])
# → Ok((value = (verbose = true,), remaining = ["--child-flag", "arg"]))
```

# See Also
- [`tryoptparse`](@ref): the entrypoint to invoke the partial parser
"""
partial(p::AbstractParser{T, E, S}) where {T, E, S} = Partial{T, E, S, typeof(p)}(p)

struct Partial{T, E, S, P <: AbstractParser{T, E, S}}
    parser::P
end

@autospecialize pp function tryoptparse(
        pp::Partial{T, E, S},
        args::Vector{String}
    )::ParseResult{Tuple{T, Vector{String}}, Union{E, MainError}} where {T, E, S}

    UE = Union{E, MainError}
    RT = Tuple{T, Vector{String}}
    parser = pp.parser
    canonical_argv, _ = normalize_argv(args)
    ctx = Context{S}(buffer = canonical_argv, state = parser.initialState, usage = usage(parser))
    skipped = String[]

    while ctx_length(ctx) > 0
        mayberesult = parse(parser, ctx)::InnerParseResult{S, E}

        if is_error(mayberesult)
            if res_num_consumed(mayberesult) > 0
                # real error — parser recognized something but couldn't handle it
                return Result{RT, UE}(typedErr(UE, res_error(err)))
            end
            # parser doesn't recognize this token — skip it
            push!(skipped, ctx_peek(ctx))
            ctx = ctx_consume(ctx, 1)
            continue
        end
        result = unwrap(mayberesult)

        previous_buffer = ctx_remaining(ctx)
        ctx = res_nextctx(result)

        if no_progress(previous_buffer, ctx)
            # parser doesn't recognize this token — skip it
            push!(skipped, ctx_peek(ctx))
            ctx = ctx_consume(ctx, 1)
            continue
        end
    end

    state = ctx_state(ctx)
    res = complete(parser, state)::ParseResult{T, E}

    remaining = append!(skipped, ctx_remaining(ctx))

    if is_error(res)
        return Result{RT, UE}(typedErr(UE, unwrap_error(res)))
    else
        return Result{RT, UE}(typedOk(RT, (unwrap(res), remaining)))
    end
end

# ─── Lifted parser entrypoints ───────────────────────────────────────────────

"""
    lift(::Type{T}) where {T<:AbstractLiftedParser}

Retrieve the parser associated with a struct type generated by [`@parser`](@ref).

`@parser struct Config ... end` defines `Config <: AbstractLiftedParser` and
registers a per-type `lift` method so that `lift(Config)` returns the parser
value. This lets you refer to the parser via its type and compose it into
larger trees without keeping an explicit binding:

```julia
@parser struct StatusCmd
    "Short"
    short = flag("-s", "--short")
end

cmd = command("status", lift(StatusCmd))
```

The entrypoints also accept the type directly:

```julia
optparse(Config, args)
```

# See Also
- [`@parser`](@ref)
- [`AbstractLiftedParser`](@ref)
"""
function lift end

function lift(::Type{T}) where {T<:AbstractLiftedParser}
    error("no `lift` method is defined for $T. Types annotated as " *
          "AbstractLiftedParser must register a lift method, which the " *
          "@parser macro does automatically. If you declared the supertype " *
          "by hand, define OptParse.lift(::Type{$T}).")
end

@autospecialize T function optparse(::Type{T}, args::Vector{String}) where {T<:AbstractLiftedParser}
    return optparse(lift(T), args)
end

@autospecialize T function tryoptparse(::Type{T}, args::Vector{String}) where {T<:AbstractLiftedParser}
    return tryoptparse(lift(T), args)
end

@autospecialize T function runparse(::Type{T}, argv::Vector{String}; kw...) where {T<:AbstractLiftedParser}
    return runparse(lift(T), argv; kw...)
end
