module OptParse

# Check whether we are compiling with juliac
using Preferences
const juliac = @load_preference("juliac", false)

using Accessors: @o, IndexLens, PropertyLens, insert, set
using WrappedUnions: @unionsplit, @wrapped,
    #=conflicts with the unwrap from ErrorTypes.jl=#
    unwrap as unwrapunion

using ErrorTypes: @?, Err, ErrorTypes, Ok, Option, Result, ResultConstructor, base, is_error,
    none, some, unwrap, unwrap_error

using UUIDs: UUID, uuid_version

using StructUtils

export
    @?,
    @constant,
    @parser,
    AbstractLiftedParser,
    HelpRequest,
    arg,
    optparse,
    choice,
    combine,
    concat,
    construct,
    construct_exact,
    command,
    default,
    flag,
    flt,
    flt32,
    flt64,
    switch,
    generate_help,
    help,
    helpcommand,
    hidden,
    i16,
    i32,
    i64,
    i8,
    integer,
    identifier,
    lift,
    many,
    many1,
    record,
    option,
    optional,
    or,
    path,
    print_help,
    repeated,
    runparse,
    str,
    sequence,
    tryoptparse,
    partial,
    u16,
    u32,
    u64,
    u8,
    uuid,
    valuetype

public AbstractParseError, AbstractParser, AbstractValueParser, validate


abstract type AbstractParser{T, E, S, P, R} end

"""
    AbstractLiftedParser

Marker supertype automatically applied to structs generated by [`@parser`](@ref).

Types `<: AbstractLiftedParser` carry an associated parser accessible via
[`lift(T)`](@ref) and are accepted directly by the entrypoints
(`optparse(T, args)`, `tryoptparse(T, args)`, `runparse(T, args)`).

# See Also
- [`@parser`](@ref)
- [`lift`](@ref)
"""
abstract type AbstractLiftedParser end

tval(::Type{<:AbstractParser{T}}) where {T} = T
tval(::AbstractParser{T}) where {T} = T

terr(::Type{<:AbstractParser{T, E}}) where {T, E} = E
terr(::AbstractParser{T, E}) where {T, E} = E

tstate(::Type{<:AbstractParser{T, E, S}}) where {T, E, S} = S
tstate(::AbstractParser{T, E, S}) where {T, E, S} = S

ptypes(::Type{<:AbstractParser{T, E, S, P}}) where {T, E, S, P} = P
ptypes(::AbstractParser{T, E, S, P}) where {T, E, S, P} = P

priority(::Type{<:AbstractParser{T, E, S, P, R}}) where {T, E, S, P, R} = R
priority(::AbstractParser{T, E, S, P, R}) where {T, E, S, P, R} = R

"""
    valuetype(parser_or_type)

Return the final value type produced by a parser.

This is mainly useful when you want to refer to the output type of an anonymous
parser in user code.

For application-facing dispatch, prefer constructing a named type directly with
[`construct`](@ref) and dispatching on that type instead.

# Examples
```jldoctest
julia> using OptParse

julia> greet = command("greet", record((
           cmd = @constant(:greet),
           name = option("-n", str("NAME")),
       )));

julia> const Greet = valuetype(greet);

julia> Greet
@NamedTuple{cmd::Val{:greet}, name::String}
```

A common pattern is to define a stable alias once and dispatch on it later when
you do not want to introduce a dedicated struct type.

For named types generated by [`@parser`](@ref), the struct itself is the valued
type and can be dispatched on directly. Use [`lift`](@ref) to retrieve the
associated parser.

# See Also
- [`optparse`](@ref)
- [`tryoptparse`](@ref)
- [`construct`](@ref)
- [`lift`](@ref)
"""
valuetype(::Type{A}) where {A <: AbstractParser} = tval(A)
valuetype(p::AbstractParser) = tval(p)

"""
    HelpRequest

Sentinel value returned by [`helpcommand`](@ref).

`argv` stores the help scope that should be passed to [`generate_help`](@ref).
For example, parsing `["help", "remote", "add"]` with `helpcommand()` yields
`HelpRequest(["remote", "add"])`.

This value is mainly useful together with higher-level runners such as
[`runparse`](@ref), which can interpret it and render the corresponding help
page.
"""
struct HelpRequest
    argv::Vector{String}
end

include("utils.jl")
include("core/usage/usage.jl")
include("core/help/help.jl")
include("core/context.jl")
include("core/errors.jl")
include("core/parseresult.jl")
include("parsers/parser.jl")
include("display/parser_show.jl")

"""
    normalize_argv(argv) -> (expanded, origin)

Expands bundled boolean short flags:
    "-abc" -> "-a", "-b", "-c"

Rules:
- Only expand before `--`
- Do not expand tokens starting with "--"
- After `--`, tokens are untouched

Returns:
- expanded::Vector{String}
- origin::Vector{Int}  (expanded index -> original argv index)
"""
function normalize_argv(argv::Vector{String})
    expanded = String[]
    origin = Int[]
    optterm = false

    for (i, tok) in pairs(argv)
        if tok == "--"
            optterm = true
            push!(expanded, tok); push!(origin, i)
            continue
        end

        if !optterm && startswith(tok, "-") && !startswith(tok, "--") && lastindex(tok) > 2
            # "-abc" => "-a","-b","-c"
            for c in tok[2:end]
                push!(expanded, "-" * string(c))
                push!(origin, i)
            end
        else
            push!(expanded, tok); push!(origin, i)
        end
    end

    return expanded, origin
end


function no_progress(previous_buffer, @nospecialize(ctx))
    return ctx_length(ctx) > 0 &&
        ctx_length(ctx) == length(previous_buffer) &&
        ctx_remaining(ctx) == previous_buffer
end


@autospecialize pp function recover_usage_context(
        pp::AbstractParser{T, E, S}, argv::Vector{String}
    )::Context{S} where {T, E, S}
    canonical_argv, _ = normalize_argv(argv)
    ctx = Context{S}(buffer = canonical_argv, state = pp.initialState, usage = usage(pp))

    while true
        mayberesult = parse(pp, ctx)::InnerParseResult{S, E}

        if is_error(mayberesult)
            return ctx
        end
        result = unwrap(mayberesult)

        previous_buffer = ctx_remaining(ctx)
        ctx = res_nextctx(result)

        if no_progress(previous_buffer, ctx)
            # Top-level progress guard: a parser must not report success while leaving argv unchanged.
            return ctx
        end

        ctx_length(ctx) > 0 || break
    end

    return ctx
end

"""
    build_help_doc(parser, argv)

Build a focused help document for `argv` from `parser`.

This is a structured, cold-path helper used by OptParse's help and error
rendering machinery. It replays enough parser state to determine the most
relevant help scope, then returns a `HelpDoc` for that scope.

Unlike `generate_help`, this function returns the intermediate help document
rather than rendered text. It is useful if you want to inspect or render the
focused help information yourself.

# Examples
```jldoctest
julia> using OptParse

julia> parser = command("serve", record((
           host = option("--host", str("HOST")),
           verbose = flag("-v", "--verbose"),
       )));

julia> doc = OptParse.build_help_doc(parser, ["serve", "--unknown"]);

julia> doc.prefix
1-element Vector{String}:
 "serve"
```

# See Also
- `generate_help`
- `OptParse.render_helpdoc`
"""
@autospecialize parser function build_help_doc(parser, argv)
    ctx = recover_usage_context(parser, argv)
    return focused_helpdoc(parser, ctx, String[], root_overlay_context())::HelpDoc
end

"""
    generate_help(parser, argv; progname = "")

Generate a rendered help page for `argv` from `parser`.

This is a high-level convenience wrapper around `build_help_doc` and
`OptParse.render_helpdoc`. It does not decide when help should be shown; it only
derives and renders the focused help page for the given parser and argument
vector.

This is useful if you want to handle `--help`, help subcommands, or other
application-specific help triggers yourself while still reusing OptParse's help
generation.

# Keyword Arguments
- `progname::AbstractString = ""`: Program name prefix to render in the usage line

# Examples
```jldoctest
julia> using OptParse

julia> parser = command("serve", record((
           host = option("--host", str("HOST")),
           verbose = flag("-v", "--verbose"),
       )));

julia> print(OptParse.generate_help(parser, ["serve"]; progname = "prog"))

Usage: prog serve --host <HOST> [OPTIONS]

Options:
   --host <HOST>    required

   -v, --verbose

```

# See Also
- `build_help_doc`
- [`optparse`](@ref)
- [`tryoptparse`](@ref)
"""
@autospecialize parser generate_help(parser, argv; progname = "") = render_helpdoc(build_help_doc(parser, argv); progname)

"""
    print_help(io, parser, argv; progname = "")

Render and print the focused help page for `argv` from `parser`.

This is a small convenience wrapper around [`generate_help`](@ref). It is useful
when you want to route help output to a chosen `IO` stream, such as `stdout`,
`stderr`, or an in-memory buffer.

# Keyword Arguments
- `progname::AbstractString = ""`: Program name prefix to render in the usage line

# Returns
Returns `nothing` after writing the rendered help text to `io`.

# See Also
- [`generate_help`](@ref)
- [`runparse`](@ref)
"""
@autospecialize parser function print_help(io, parser, argv; progname = "")
    helpstr = generate_help(parser, argv; progname)
    print(io, helpstr)
    return nothing
end


include("entrypoints.jl")


using PrecompileTools: @compile_workload
@compile_workload begin
    # Build a representative parser exercising all constructor + leaf types
    _pc_parser = or(
        command(
            "run", record(
                (
                    host = default(option("--host", str("HOST")), "localhost"),
                    port = default(option(("-p", "--port"), integer(; min = 1, max = 65535)), 8080),
                    verbose = switch("-v", "--verbose"),
                    debug = flag("-d"),
                    file = arg(str("FILE")),
                    mode = @constant(:run),
                )
            )
        ),
        command(
            "test", record(
                (
                    filter = default(option("--filter", str("PATTERN")), ""),
                    count = default(option("-n", integer()), 1),
                    mode = @constant(:test),
                )
            )
        ),
    )

    # Exercise parse + complete (success path)
    tryoptparse(_pc_parser, ["run", "--host", "example.com", "-p", "3000", "-v", "out.txt"])
    # Exercise parse + complete (different branch)
    tryoptparse(_pc_parser, ["test", "--filter", "foo", "-n", "5"])
    # Exercise error path
    tryoptparse(_pc_parser, ["unknown"])

    optparse(_pc_parser, String["run", "--host", "example.com", "-p", "3000", "-v", "out.txt"])

    runparse(_pc_parser, String["run", "--host", "example.com", "-p", "3000", "-v", "out.txt"])
    # Exercise help generation (cold path but useful)
    generate_help(_pc_parser, String[])
end


end # module OptParse
